### ISSUE TITLE
unmarshalPayload: index out of range (v1.29.0)

### ISSUE THREAD

**Issue by AlexandreYang** [gosnmp/gosnmp#311]
Hey, first thanks for the work on gosnmp !

I'm seeing the following error using v1.29.0

Snmp version: 3
Device Type: APC UPS (sysobjectid: 1.3.6.1.4.1.318.1.3.27)

```
runtime error: index out of range [0] with length 0
Stack:goroutine 291 [running]:
github.com/gosnmp/gosnmp.(*GoSNMP).send.func1(0xc000a3b2b0)
	.../github.com/gosnmp/gosnmp@v1.29.0/marshal.go:326 +0xa1
panic(0x3e23c20, 0xc00126dfe0)
	/root/.gimme/versions/go1.14.12.linux.amd64/src/runtime/panic.go:969 +0x166
github.com/gosnmp/gosnmp.(*GoSNMP).unmarshalPayload(0xc000920240, 0x0, 0x0, 0x0, 0x0, 0xc000789260, 0x0, 0x0)
	.../github.com/gosnmp/gosnmp@v1.29.0/marshal.go:872 +0x536
github.com/gosnmp/gosnmp.(*GoSNMP).sendOneRequest(0xc000920240, 0xc00087c460, 0x1, 0x0, 0xe0, 0x3f91980)
	.../github.com/gosnmp/gosnmp@v1.29.0/marshal.go:269 +0x7cd
github.com/gosnmp/gosnmp.(*GoSNMP).send(0xc000920240, 0xc00087c460, 0xc0012c6001, 0x0, 0x0, 0x0)
	.../github.com/gosnmp/gosnmp@v1.29.0/marshal.go:349 +0xef
github.com/gosnmp/gosnmp.(*GoSNMP).Get(0xc000920240, 0xc00035e780, 0x27, 0x28, 0x1, 0x1882910, 0xc00027ab40)
	.../github.com/gosnmp/gosnmp@v1.29.0/gosnmp.go:363 +0x154
```

Seems raised by this line: https://github.com/gosnmp/gosnmp/blob/bd1d291881777450abc4399ee2fd0bb2795eb18b/marshal.go#L872

With `unmarshalPayload` being called with empty list of `packet` and cursor being `0`.

It looks like we don't handle errors here if `decryptPacket` returns an error:
https://github.com/gosnmp/gosnmp/blob/bd1d291881777450abc4399ee2fd0bb2795eb18b/marshal.go#L266

I will try to get an example payload triggering this issue and share it here.

**Comment by TimRots** [comment]
> I will try to get an example payload triggering this issue and share it here.

That would be much appreciated. Thank you for opening this issue @AlexandreYang.

**Comment by AlexandreYang** [comment]
It's taking a bit more time to get an example, but will share here as soon as I have it.

**Comment by AlexandreYang** [comment]
Sharing another similar case with also a APC UPS device.

<details>
  <summary>Click to expand!</summary>

```
# using SNMPGET
# device type APC UPS
error getting oids `[1.3.6.1.4.1.318.1.1.1.2.2.6.0 1.3.6.1.4.1.318.1.1.1.2.2.4.0 1.3.6.1.4.1.318.1.1.1.2.2.3.0 1.3.6.1.4.1.318.1.1.1.2.2.2.0 1.3.6.1.4.1.318.1.1.1.2.2.1.0 1.3.6.1.4.1.318.1.1.1.3.3.4.0 1.3.6.1.4.1.318.1.1.1.3.3.1.0 1.3.6.1.4.1.318.1.1.1.4.3.4.0 1.3.6.1.4.1.318.1.1.1.3.2.5.0 1.3.6.1.4.1.318.1.1.1.4.2.3.0 1.3.6.1.4.1.318.1.1.1.2.1.2.0 1.3.6.1.4.1.318.1.1.1.7.2.3.0 1.3.6.1.4.1.318.1.1.1.11.1.1.0 1.3.6.1.4.1.318.1.1.1.11.1.1.0 1.3.6.1.4.1.318.1.1.1.11.1.1.0 1.3.6.1.4.1.318.1.1.1.11.1.1.0 1.3.6.1.4.1.318.1.1.1.11.1.1.0 1.3.6.1.4.1.318.1.1.1.11.1.1.0 1.3.6.1.4.1.318.1.1.1.11.1.1.0 1.3.6.1.2.1.6.5.0 1.3.6.1.2.1.6.6.0 1.3.6.1.2.1.6.7.0 1.3.6.1.2.1.6.8.0 1.3.6.1.2.1.6.9.0 1.3.6.1.2.1.6.17.0 1.3.6.1.2.1.6.18.0 1.3.6.1.2.1.6.12.0 1.3.6.1.2.1.6.14.0 1.3.6.1.2.1.6.15.0 1.3.6.1.2.1.7.8.0 1.3.6.1.2.1.7.2.0 1.3.6.1.2.1.7.3.0 1.3.6.1.2.1.7.9.0 1.3.6.1.4.1.318.1.1.1.1.1.1.0 1.3.6.1.4.1.318.1.1.1.1.2.3.0 1.3.6.1.4.1.318.1.1.1.1.2.1.0 1.3.6.1.4.1.318.1.1.1.1.1.2.0 1.3.6.1.2.1.1.5.0 1.3.6.1.2.1.1.3.0]`: recover: runtime error: index out of range [33] with length 33
Stack:goroutine 1 [running]:
github.com/gosnmp/gosnmp.(*GoSNMP).send.func1(0xc000c6e8c8)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/gosnmp/gosnmp@v1.29.0/marshal.go:326 +0xa1
panic(0x3e23c20, 0xc000f4ef40)
	/root/.gimme/versions/go1.14.12.linux.amd64/src/runtime/panic.go:969 +0x166
github.com/gosnmp/gosnmp.parseLength(0xc00011b254, 0x21, 0x23, 0x77, 0x54)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/gosnmp/gosnmp@v1.29.0/helper.go:585 +0x8e
github.com/gosnmp/gosnmp.(*GoSNMP).decryptPacket(0xc0001e9680, 0xc00011b200, 0x75, 0x77, 0x54, 0xc0010448c0, 0x0, 0x0, 0x77, 0x65, ...)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/gosnmp/gosnmp@v1.29.0/v3.go:441 +0xc5
github.com/gosnmp/gosnmp.(*GoSNMP).sendOneRequest(0xc0001e9680, 0xc0006bbb20, 0x1, 0x0, 0xe0, 0x3f91980)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/gosnmp/gosnmp@v1.29.0/marshal.go:266 +0x787
github.com/gosnmp/gosnmp.(*GoSNMP).send(0xc0001e9680, 0xc0006bbb20, 0xc000f78a01, 0x0, 0x0, 0x0)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/gosnmp/gosnmp@v1.29.0/marshal.go:349 +0xef
github.com/gosnmp/gosnmp.(*GoSNMP).Get(0xc0001e9680, 0xc000394780, 0x27, 0x28, 0x1, 0x1882910, 0xc0000c8e80)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/gosnmp/gosnmp@v1.29.0/gosnmp.go:363 +0x154
github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp.(*snmpSession).Get(0xc0001e9680, 0xc000394780, 0x27, 0x28, 0x1, 0x0, 0x7fc5dd465b98)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp/session.go:97 +0x4b
github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp.doDoFetchScalarOids(0x4668e80, 0xc0001e9680, 0xc000394780, 0x27, 0x28, 0xc000b51b60, 0x1, 0x0)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp/fetch_scalar.go:109 +0x10a
github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp.doFetchScalarOids(0x4668e80, 0xc0001e9680, 0xc000394780, 0x27, 0x28, 0x28, 0x3c, 0xc000394780)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp/fetch_scalar.go:98 +0x383
github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp.fetchScalarOids(0x4668e80, 0xc0001e9680, 0xc000394780, 0x27, 0x28, 0x1, 0x1, 0x0)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp/fetch_scalar.go:34 +0x5a
github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp.fetchScalarOidsWithBatching(0x4668e80, 0xc0001e9680, 0xc000394780, 0x27, 0x28, 0x3c, 0x0, 0x0, 0xc000c6ece8)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp/fetch_scalar.go:22 +0x299
github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp.fetchValues(0x4668e80, 0xc0001e9680, 0xc000e52500, 0xd, 0xa1, 0x0, 0x0, 0x60ccfb3, 0x1, 0x2, ...)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp/fetch.go:20 +0x84
github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp.(*Check).processSnmpMetrics(0xc0000d4000, 0xc000c6f440, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp/snmp.go:96 +0x31f
github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp.(*Check).Run(0xc0000d4000, 0x7feac7b6a, 0x62ca980)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/snmp/snmp.go:40 +0x15a
github.com/DataDog/datadog-agent/cmd/agent/common/commands.runCheck(0x467de80, 0xc0000d4000, 0xc000562000, 0x6bc)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/agent/common/commands/check.go:439 +0xf9
github.com/DataDog/datadog-agent/cmd/agent/common/commands.Check.func1(0xc000690000, 0xc0002ea810, 0x1, 0x3, 0x0, 0x0)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/agent/common/commands/check.go:295 +0x1980
github.com/spf13/cobra.(*Command).execute(0xc000690000, 0xc0002ea7e0, 0x3, 0x3, 0xc000690000, 0xc0002ea7e0)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x6094700, 0x0, 0xffffffff, 0xc00010a058)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/cmd/agent/main.go:18 +0x2d

goroutine 6 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/root/.gimme/versions/go1.14.12.linux.amd64/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc00005c690, 0x0)
	/root/.gimme/versions/go1.14.12.linux.amd64/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc00005c680)
	/root/.gimme/versions/go1.14.12.linux.amd64/src/sync/cond.go:56 +0x9d
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc000162000, 0x0)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/cihub/seelog@v0.0.0-20151216151435-d2c6e5aa9fbf/behavior_asynclooplogger.go:50 +0x8a
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc000162000)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/cihub/seelog@v0.0.0-20151216151435-d2c6e5aa9fbf/behavior_asynclooplogger.go:63 +0x42
created by github.com/cihub/seelog.NewAsyncLoopLogger
	/.omnibus/src/datadog-agent/pkg/mod/github.com/cihub/seelog@v0.0.0-20151216151435-d2c6e5aa9fbf/behavior_asynclooplogger.go:40 +0x9c

goroutine 7 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/root/.gimme/versions/go1.14.12.linux.amd64/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc00005c810, 0x0)
	/root/.gimme/versions/go1.14.12.linux.amd64/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc00005c800)
	/root/.gimme/versions/go1.14.12.linux.amd64/src/sync/cond.go:56 +0x9d
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc000162120, 0x0)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/cihub/seelog@v0.0.0-20151216151435-d2c6e5aa9fbf/behavior_asynclooplogger.go:50 +0x8a
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc000162120)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/cihub/seelog@v0.0.0-20151216151435-d2c6e5aa9fbf/behavior_asynclooplogger.go:63 +0x42
created by github.com/cihub/seelog.NewAsyncLoopLogger
	/.omnibus/src/datadog-agent/pkg/mod/github.com/cihub/seelog@v0.0.0-20151216151435-d2c6e5aa9fbf/behavior_asynclooplogger.go:40 +0x9c

goroutine 12 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc000555a40, 0xc000559440)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0xd5
created by github.com/patrickmn/go-cache.runJanitor
	/.omnibus/src/datadog-agent/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0xa9

goroutine 20 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x62cb040)
	/.omnibus/src/datadog-agent/pkg/mod/k8s.io/klog@v1.0.1-0.20200310124935-4ad0115ba9e4/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/.omnibus/src/datadog-agent/pkg/mod/k8s.io/klog@v1.0.1-0.20200310124935-4ad0115ba9e4/klog.go:411 +0xd6

goroutine 21 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x62cb120)
	/.omnibus/src/datadog-agent/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:1107 +0x8b
created by k8s.io/klog/v2.init.0
	/.omnibus/src/datadog-agent/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:416 +0xd6

goroutine 161 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc00065dd80, 0xc00047ad80)
	/.omnibus/src/datadog-agent/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0xd5
created by github.com/patrickmn/go-cache.runJanitor
	/.omnibus/src/datadog-agent/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0xa9

goroutine 180 [select]:
github.com/DataDog/datadog-agent/pkg/tagger/local.(*Tagger).run(0xc00095fa80, 0xc0005528b8, 0x4164e58)
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/local/tagger.go:95 +0x163
created by github.com/DataDog/datadog-agent/pkg/tagger/local.(*Tagger).Init
	/.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/tagger/local/tagger.go:87 +0x8a

goroutine 145 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/root/.gimme/versions/go1.14.12.linux.amd64/
      No traceback

```
</details>

**Comment by TimRots** [comment]
Hi @AlexandreYang , sharing another example was helpful to reproduce the error.  :)

Could you give #323 a first review? Added error handling to the ``x.decryptPacket`` call in ``sendOneRequest()`` and added validation to ``unmarshalPayload()``, to prevent the panic you've reported from reoccurring.

Thanks!

**Comment by AlexandreYang** [comment]
Sure, thanks for the PR.

**Comment by AlexandreYang** [comment]
It seems that in the second case is about a panic from `parseLength`, related to this line https://github.com/gosnmp/gosnmp/blob/v1.29.0/helper.go#L585
